# This is a basic workflow to help you get started with Actions

name: CI- name: Deploy to Heroku
  uses: AkhileshNS/heroku-deploy@v3.0.0
  with: gitub 
    # This will be used for authentication. You can find it in your heroku homepage account settings
    heroku_api_key: 3f143ca4-6f10-48d3-9b27-ceee93277516
    # Email that you use with heroku
    heroku_email: nixeli84@tcapsstudent.net
    # The appname to use for deploying/updating
    heroku_app_name: will
    # An optional buildpack to use when creating the heroku application
    buildpack: # elijah 
    # The branch that you would like to deploy to Heroku
    branch: # optional, default is HEAD
    # Set this to true if you don't want to use --force when switching branches
    dontuseforce: # optional
    # Will deploy using Dockerfile in project root.
    usedocker: # optional

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: yes
  push: yes  
    branches: [ master ]
  pull_request: yes
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
